Update with latest feature request guidance
OfficeDev/office-scripts-docs pull request #260
Opened 2021-04-15 23:10 UTC by AlexJerabek

2021-04-15 23:11 UTC, opbld33 commented
Docs Build status updates of commit _[1d81b86](https://github.com/OfficeDev/office-scripts-docs/commits/1d81b86fc1d18a1b8dd50f8de4ea40893afd5e56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/dev/scripts/index?branch=pr-en-us-260) | [Details](#user-content-c88dd6b4d05547f96d3f2ee343853bd2-a681a69c)
[Issue_Template.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/Issue_Template.md) | :white_check_mark:Succeeded | |
[README.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/README.md) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/docfx.json) | :white_check_mark:Succeeded | |

<a id="c88dd6b4d05547f96d3f2ee343853bd2-a681a69c"></a>
### [docs/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/index.md)
 - **Line 147, Column 34**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '(https://techcommunity.microsoft.com/t5/excel/bd-p/ExcelGeneral)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202104152310467427-260%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IaKj4voXD5cbIWKPAXXECaCJsqfORuFHnB%2B6JsozxVM%3D&st=2021-04-15T23%3A06%3A21Z&se=2021-05-16T23%3A11%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 23:12 UTC, opbld32 commented
Docs Build status updates of commit _[07ccd74](https://github.com/OfficeDev/office-scripts-docs/commits/07ccd746d5da27d21e0966f8ea41d27a30eb1a54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Issue_Template.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/Issue_Template.md) | :white_check_mark:Succeeded | |
[README.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/README.md) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/scripts/index?branch=pr-en-us-260) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202104152311544758-260%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hideXy3fcxlEMsbX3ordSMIOEuUb2EIzPZtaDnZNQRI%3D&st=2021-04-15T23%3A07%3A27Z&se=2021-05-16T23%3A12%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 23:21 UTC, lindalu-MSFT requested changes

2021-04-15 23:21 UTC, lindalu-MSFT commented on README.md
> +- To submit a feature request for Office Scripts, post your idea the Excel Tech Community (https://techcommunity.microsoft.com/t5/excel/bd-p/ExcelGeneral), or if the feature request already exists th
@AlexJerabek This doesn't seem quite right. The ExcelGeneral community only has discussion and blogs. They do not have a "feature request" section (called "Ideas" in the M365 dev platform space) so there is no way to vote. Also, I see that just above in line 26, the topic points people to Stack. 
1. We want to suggest people ask Office Script questions on Microsoft Q+A
2. We want "ideasFeature requests/suggestions that did go to UserVoice to go to TC Ideas so they can get voted on. But, the only Ideas section we have is in Microsoft 365 develop platform. I will suggest we add a tag there, for feature requests?

2021-04-15 23:26 UTC, AlexJerabek commented on README.md
> +- To submit a feature request for Office Scripts, post your idea the Excel Tech Community (https://techcommunity.microsoft.com/t5/excel/bd-p/ExcelGeneral), or if the feature request already exists th
Oh, I misunderstood that "Ideas section" point in our related thread.

2021-04-15 23:31 UTC, lindalu-MSFT commented
Yes, I misunderstood too. I thought the ExcelGeneral "consumer" Tech Community had created the Ideas section for suggestions, but when I verified I only saw discussion and blogs. So, for UserVoice-type suggestions, this doesn't seem the right place. Either they create Excel Ideas forum and include a tag for Office Scripts -OR- we return to our original plan which was to add an office-scripts tag to the Microsoft 365 dev platform Ideas forum we just created.


From: Alex Jerabek ***@***.***>
Sent: 15 April, 2021 4:27 PM
To: OfficeDev/office-scripts-docs ***@***.***>
Cc: Linda Lu Cannon ***@***.***>; Review requested ***@***.***>
Subject: Re: [OfficeDev/office-scripts-docs] Update with latest feature request guidance (#260)


@AlexJerabek commented on this pull request.

________________________________

In README.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-scripts-docs%2Fpull%2F260%23discussion_r614459624&data=04%7C01%7CLinda.Cannon%40microsoft.com%7C63e6c0bde5dd43ad81e908d90065f63f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637541260190032762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nr1Oly4gtKhp1PhnfOHRYnzXZSSyXNpPZris7ynC9MI%3D&reserved=0>:

> @@ -25,7 +25,7 @@ If your issue is not related to the Office Scripts documentation, please post it



 - To ask a question about designing Office Scripts or the Office.js API that runs Office Scripts, post your question to Stack Overflow and tag it with the "office-scripts" tag (https://stackoverflow.com/questions/tagged/office-scripts).

 - To report an issue with the Office.js API, create the issue in the [OfficeDev/office-js repository](https://github.com/OfficeDev/office-js), which members of the product team monitor for customer-reported issues.

-- To submit a feature request for Office Scripts, post your idea to [Microsoft Q&A](https://docs.microsoft.com/answers/products/m365), or if the feature request already exists there, add your vote for it. Be sure to use the "Office-Scripts-Dev" tag when asking for your feature.

+- To submit a feature request for Office Scripts, post your idea the Excel Tech Community (https://techcommunity.microsoft.com/t5/excel/bd-p/ExcelGeneral), or if the feature request already exists there, add your vote for it. Be sure to use the "Office Scripts" tag when asking for your feature.

Oh, I misunderstood that "Ideas section" point in our related thread.

-
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-scripts-docs%2Fpull%2F260%23discussion_r614459624&data=04%7C01%7CLinda.Cannon%40microsoft.com%7C63e6c0bde5dd43ad81e908d90065f63f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637541260190042757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6TlXddojDSIhsv5P0Pfw%2Bu9uqoi1DEyC7%2BnUVg%2F1FcQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHKC5M3IL7RL7CB2XOYURKLTI5Y4DANCNFSM43ANA3MA&data=04%7C01%7CLinda.Cannon%40microsoft.com%7C63e6c0bde5dd43ad81e908d90065f63f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637541260190042757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kD3W%2FGdkr7uV0%2FMqRAnl%2Ba64Ht6FW6D9I3v6oPC0yl8%3D&reserved=0>.

2021-04-16 18:40 UTC, opbld33 commented
Docs Build status updates of commit _[199a4fb](https://github.com/OfficeDev/office-scripts-docs/commits/199a4fbb0265d75bc6b2d7083c19a3381de31d68)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-db8221a4)

<a id="db8221a4"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202104161840121003-260%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V6IqPjvYxmnQvueTvEqy%2FjPSFREPmq6BrBKRrXrjPAg%3D&st=2021-04-16T18%3A35%3A51Z&se=2021-05-17T18%3A40%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 18:41 UTC, AlexJerabek commented
@lindalu-MSFT,
Based on our offline discussion with Cuong, it seems like the right thing to do is point feature requests at UserVoice until  they transition to Feedback Hub. Does that match your understanding?

2021-04-16 18:44 UTC, lindalu-MSFT commented
@AlexJerabek That works for me, as long as UserVoice remains up for Excel consumer.

2021-04-16 18:46 UTC, AlexJerabek commented
@lindalu-MSFT Cool, thanks! I'll keep an eye on UserVoice. We can use M365 Q&A as a contingency plan in case UserVoice goes down before Feedback Hub for Scripts is enabled.

2021-04-16 18:54 UTC, opbld31 commented
Docs Build status updates of commit _[199a4fb](https://github.com/OfficeDev/office-scripts-docs/commits/199a4fbb0265d75bc6b2d7083c19a3381de31d68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Issue_Template.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/Issue_Template.md) | :white_check_mark:Succeeded | |
[README.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/README.md) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/index.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-FeatureRequests/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/scripts/index?branch=pr-en-us-260) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202104161853587627-260%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CWPAnpPSkDA11hlMjmHFYTDopZDW0qkw3F6tbZ62aRM%3D&st=2021-04-16T18%3A49%3A29Z&se=2021-05-17T18%3A54%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 22:43 UTC, merged