[excel] (Samples) Adding guidance on long workbook names
OfficeDev/office-scripts-docs pull request #565
Opened 2022-12-27 22:57 UTC by AlexJerabek

Fixes #560.

This PR adds further guidance around the scenario where the combined workbooks have long names.

2023-01-03 18:47 UTC, davidchesnut requested changes
Looks good, just a couple notes added.

2023-01-03 18:47 UTC, davidchesnut commented on docs/resources/samples/combine-worksheets-into-single-workbook.md
> +
In the previous TypeScript, it needs to be broken across the foreach loop as follows (not sure if you want to include this specific or not, but just pointing out this is not a simple "copy paste" operation.

```typescript
function main(workbook: ExcelScript.Workbook, workbookName: string, worksheetInformation: WorksheetData[]) {
  let worksheetNumber = 1;
  
  // Add each new worksheet.
  worksheetInformation.forEach((value) => {
    let worksheetName = `${workbookName}.${value.name}`;
    let sheet = workbook.addWorksheet(`${worksheetName.substr(0, 30)}${worksheetNumber++}`);
```

2023-01-03 21:04 UTC, AlexJerabek commented
Thanks @davidchesnut! I've applied your feedback to the PR.

2023-01-04 23:08 UTC, AlexJerabek commented
Approved offline. Merging!

2023-01-04 23:08 UTC, merged

2023-01-05 00:28 UTC, davidchesnut reviewed
Tested and looks great! (belated approve.)